language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  matrix:
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
install:
  - pip install 'coverage<4' # covarage>=4 has issues with python3
  - pip install Django==$DJANGO_VERSION coveralls
  - python setup.py install
script: coverage run --source='linaro_django_pagination' --omit *runner*,*test_project* setup.py test
after_success:
  - coveralls
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.9 # Unsupported
    - python: "3.3"
      env: DJANGO_VERSION=1.9 # ImportError: cannot import name find_spec
    - python: "3.5"
      env: DJANGO_VERSION=1.7 # AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
    - python: "3.5"
      env: DJANGO_VERSION=1.6 # AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
