language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  matrix:
    - DJANGO_VERSION=1.2
    - DJANGO_VERSION=1.3
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
install:
  - pip install 'coverage<4' # coverage>=4 has issues with python3
  - pip install -q Django==$DJANGO_VERSION coveralls
  - python setup.py egg_info
script: coverage run --source='linaro_django_pagination' --omit *runner*,*test_project* setup.py test
after_success:
  - coveralls
matrix:
  include:
    - python: "2.6"
      env: DJANGO_VERSION=1.4
    - python: "2.6"
      env: DJANGO_VERSION=1.5
    - python: "2.6"
      env: DJANGO_VERSION=1.6
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.2 # Unsupported
    - python: "3.2"
      env: DJANGO_VERSION=1.3 # Unsupported
    - python: "3.2"
      env: DJANGO_VERSION=1.4 # Unsupported
    - python: "3.2"
      env: DJANGO_VERSION=1.9 # Unsupported
    - python: "3.3"
      env: DJANGO_VERSION=1.9 # ImportError: cannot import name find_spec
    - python: "3.3"
      env: DJANGO_VERSION=1.2 # Unsupported
    - python: "3.3"
      env: DJANGO_VERSION=1.3 # Unsupported
    - python: "3.3"
      env: DJANGO_VERSION=1.4 # Unsupported
    - python: "3.4"
      env: DJANGO_VERSION=1.2 # Unsupported
    - python: "3.4"
      env: DJANGO_VERSION=1.3 # Unsupported
    - python: "3.4"
      env: DJANGO_VERSION=1.4 # Unsupported
    - python: "3.5"
      env: DJANGO_VERSION=1.2 # Unsupported
    - python: "3.5"
      env: DJANGO_VERSION=1.3 # Unsupported
    - python: "3.5"
      env: DJANGO_VERSION=1.4 # Unsupported
    - python: "3.5"
      env: DJANGO_VERSION=1.5 # Unsupported
    - python: "3.5"
      env: DJANGO_VERSION=1.7 # AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
    - python: "3.5"
      env: DJANGO_VERSION=1.6 # AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
